# Generated by Django 3.0.4 on 2020-04-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_email', models.CharField(max_length=225)),
                ('log_password', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_first', models.CharField(max_length=225)),
                ('reg_last', models.CharField(max_length=225)),
                ('reg_email', models.CharField(max_length=225)),
                ('reg_password', models.CharField(max_length=225)),
                ('reg_confirm_password', models.CharField(max_length=225)),
            ],
        ),
    ]
