# Generated by Django 3.0.4 on 2020-04-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first', models.CharField(max_length=225)),
                ('contact_last', models.CharField(max_length=225)),
                ('contact_email', models.CharField(max_length=225)),
                ('contact_subject', models.CharField(max_length=225)),
                ('contact_feedback', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_first', models.CharField(max_length=225)),
                ('reg_last', models.CharField(max_length=225)),
                ('reg_username', models.CharField(max_length=225)),
                ('reg_email', models.CharField(max_length=225)),
                ('reg_password', models.CharField(max_length=225)),
                ('reg_confirm_password', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
