# Generated by Django 3.0.4 on 2020-04-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0002_auto_20200405_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose_age', models.IntegerField()),
                ('diagnose_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
            ],
        ),
    ]
