# Generated by Django 3.0.4 on 2020-04-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0005_auto_20200422_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='meddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_age', models.IntegerField()),
                ('med_gender', models.CharField(default='male', max_length=10)),
            ],
        ),
    ]
