# Generated by Django 3.0.4 on 2020-05-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0007_auto_20200430_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='meddata1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_age1', models.IntegerField()),
                ('med_gender1', models.CharField(max_length=10)),
            ],
        ),
    ]
