# Generated by Django 3.0.4 on 2020-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0008_meddata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_bodydata', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bodyloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_bodyloc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subbody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_subbody', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='meddata1',
        ),
    ]
