# Generated by Django 3.0.4 on 2020-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0010_auto_20200512_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='body_data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_bodydata', models.CharField(max_length=100)),
                ('med_bodydatano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='body_loc1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_bodyloc', models.CharField(max_length=100)),
                ('med_bodylocno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sub_body1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_subbody', models.CharField(max_length=100)),
                ('med_subbodyno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='body_data',
        ),
        migrations.DeleteModel(
            name='body_loc',
        ),
        migrations.DeleteModel(
            name='sub_body',
        ),
    ]
